---
- name: Add nginx apt repo key
  apt_key:
    url: http://nginx.org/packages/keys/nginx_signing.key
    state: present

- name: Add official nginx apt repository
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx
    state: present
    filename: 'nginx'

- name: Stop and disable apache2 to free port 80 for nginx
  systemd:
    name: apache2
    state: stopped
    enabled: no
  become: yes
  ignore_errors: yes

- name: Install nginx
  apt:
    name: nginx
    state: present