---
- name: restart nginx
  become: yes
  shell: |
    set +e  # Don't stop on errors

    echo "=== Checking nginx status BEFORE restart ==="
    systemctl status nginx.service --no-pager -l || true

    echo "=== Checking port 80 usage BEFORE restart ==="
    ss -tlnp | grep :80 || echo "Port 80 not in use"

    echo "=== Killing any lingering nginx processes ==="
    systemctl stop nginx || true
    pkill -f nginx || echo "No nginx processes to kill"

    echo "=== Removing stale PID file if exists ==="
    rm -f /var/run/nginx.pid

    echo "=== Testing nginx configuration ==="
    /usr/sbin/nginx -t || true

    echo "=== Waiting 3 seconds before restart ==="
    sleep 3

    echo "=== Starting nginx ==="
    systemctl start nginx
    sleep 3

    echo "=== Checking nginx status AFTER restart ==="
    if ! systemctl is-active --quiet nginx; then
      echo "Nginx FAILED to start!"
      echo "--- SYSTEMD LOGS ---"
      journalctl -u nginx.service --no-pager -n 50 || true
      echo "--- NGINX ERROR LOG ---"
      tail -n 50 /var/log/nginx/error.log 2>/dev/null || echo "No error log found"
    else
      systemctl status nginx.service --no-pager -l || true
      echo "Nginx is running."
    fi

    exit 0
  args:
    executable: /bin/bash

- name: reload nginx
  shell: |
    echo "=== Testing nginx config before reload ==="
    if sudo /usr/sbin/nginx -t; then
      echo "=== Reloading nginx ==="
      sudo systemctl reload nginx
    else
      echo "=== Config test failed, skipping reload ==="
      exit 1
    fi