---
- name: restart nginx
  shell: |
    echo "=== Checking nginx status before restart ==="
    sudo systemctl status nginx.service --no-pager -l || true
    echo "=== Checking port 80 usage ==="
    sudo netstat -tlnp | grep :80 || echo "Port 80 not in use"
    echo "=== Testing nginx config ==="
    sudo /usr/sbin/nginx -t || true
    echo "=== Stopping nginx ==="
    sudo systemctl stop nginx || true
    echo "=== Starting nginx ==="
    sudo systemctl start nginx
    echo "=== Checking nginx status after restart ==="
    sudo systemctl status nginx.service --no-pager -l || true
    if ! sudo systemctl is-active --quiet nginx; then
      echo "=== Nginx failed to start, checking logs ==="
      sudo journalctl -xeu nginx.service --no-pager -n 50 || true
      sudo tail -20 /var/log/nginx/error.log 2>/dev/null || echo "No error log found"
      exit 1
    fi

- name: reload nginx
  shell: |
    echo "=== Testing nginx config before reload ==="
    if sudo /usr/sbin/nginx -t; then
      echo "=== Reloading nginx ==="
      sudo systemctl reload nginx
    else
      echo "=== Config test failed, skipping reload ==="
      exit 1
    fi